service: serverless-chat

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  websocketApiName: serverless-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:ap-south-1:*:*"

functions:
    connectionManager:
        handler: handler.connection_manager
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
    defaultMessage:
        handler: handler.default_message
        events:
            - websocket:
                route: $default
    getRecentMessages:
        handler: handler.get_recent_messages
        events:
            - websocket:
                route: getRecentMessages
    sendMessage:
        handler: handler.send_message
        events:
            - websocket:
                route: sendMessage
    userMigrate:
        handler: handler.user_migrate
    ping:
        handler: handler.ping
        events:
            - http:
                path: ping
                method: get


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []

  stage: ${opt:stage, self:provider.stage}
