service: serverless-chat

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  websocketApiName: serverless-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchGetItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:ap-south-1:*:*"

functions:
    connectionManager:
        handler: handlers/handler.connection_manager
        package: {}
        events:
            - websocket:
                route: $connect
                authorizer:
                  name: wsGuestTokenAuthorizer
                  resultTtlInSeconds: 0
                  identitySource:
                    - 'route.request.querystring.token'
                  type: request
            - websocket:
                route: $disconnect
    defaultMessage:
        handler: handlers/handler.default_message
        package: {}
        events:
            - websocket:
                route: $default
    getRecentMessages:
        handler: handlers/handler.get_recent_messages
        package: {}
        events:
            - websocket:
                route: getRecentMessages
    sendMessage:
        handler: handlers/handler.send_message
        package: {}
        events:
            - websocket:
                route: sendMessage
                authorizer:
#                    # name: auth    NOTE: you can either use "name" or arn" properties
#                    arn: arn:aws:lambda:us-east-1:1234567890:function:auth
#                    identitySource:
#                      - 'route.request.header.Auth'
#                      - 'route.request.querystring.Auth'
    setConversation:
        handler: handlers/handler.set_conversation
        package: {}
        events:
            - http:
                method: post
                cors:
                    origin: '*'
                    headers:
                      - Content-Type
                      - t2m-authtoken
                    allowCredentials: false
                path: set-conversation
                authorizer:
                    name: tokenAuthorizer
                    resultTtlInSeconds: 0
                    identitySource: method.request.header.t2m-authtoken
                    type: request
    userMigrate:
        handler: handlers/handler.user_migrate
        package: {}
    ping:
        handler: handlers/handler.ping
        events:
            - http:
                path: ping
                method: get
    checkUsername:
        handler: handlers/username.check_username
        package: {}
        events:
          - http:
              path: find-username
              method: get
              cors:
                  origin: '*'
                  headers:
                    - Content-Type
                    - t2m-temptoken
                  allowCredentials: false
              authorizer:
                name: tempTokenAuthorizer
                resultTtlInSeconds: 0
                identitySource: method.request.header.t2m-temptoken
                type: request
    setUsername:
      handler: handlers/username.set_username
      package: {}
      events:
        - http:
            path: set-username
            method: put
            cors:
              origin: '*'
              headers:
                - Content-Type
                - t2m-temptoken
              allowCredentials: false
            authorizer:
              name: tempTokenAuthorizer
              resultTtlInSeconds: 0
              identitySource: method.request.header.t2m-temptoken
              type: request
    getAccessTokenWS:
      handler: handlers/auth.get_tokens
      package: {}
      events:
        - http:
            path: ws-auth
            method: post
            cors:
              origin: '*'
              headers:
                - Content-Type
                - t2m-temptoken
              allowCredentials: false
            authorizer:
              name: tempTokenAuthorizer
              resultTtlInSeconds: 0
              identitySource: method.request.header.t2m-temptoken
              type: request
    tokenAuthorizer:
      handler: helpers/authorizers.user_pool_auth
      package: {}
    tempTokenAuthorizer:
      handler: helpers/authorizers.temp_token_auth
      package: {}
    guestTokenAuthorizer:
      handler: helpers/authorizers.guest_token_auth
      package: {}
#    wsTempTokenAuthorizer:
#      handler: helpers/authorizers.ws_temp_token_auth
    wsGuestTokenAuthorizer:
      handler: helpers/authorizers.ws_guest_token_auth
      package: {}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []

  stage: ${opt:stage, self:provider.stage}
